### PR TITLE
fix: backdrop -> check if mounted before setting state

### LINKED ISSUE #1376: [v4] State update warning related to BottomSheetBackdrop on closing
# Bug

After upgrading to 4.4.6 from 4.3.2, we have  occasionally noticed this warning related to `BottomSheetBackdrop` when closing the bottom sheet:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in BottomSheetBackdrop
```

BottomSheetBackdrop usage:
```
backdropComponent={backdropProps => (
  <BottomSheetBackdrop {...backdropProps} disappearsOnIndex={-1} appearsOnIndex={0} pressBehavior="close" />
)}
```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.6   |
| react-native                    | 0.67.5   |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    | 2.4.2   |

## Steps To Reproduce

It happens occasionally both on Android and iOS. 
I think it only happens with the modal component.
The warning appears when the sheet is closed (tap on backdrop, drag gesture or programmatically)

### PR DESCRIPTION
**Pull request by christophby**
closes https://github.com/gorhom/react-native-bottom-sheet/issues/1376 (has already been closed, although it hasn't been fixed yet )

## Motivation

When using the backdrop component you could get a `"Warning: Can't perform a React state update on an unmounted component [...] in BottomSheetBackdrop"` error.

This PR adds a check if the component is mounted before setting the local state to fix that issue.

### CODE REVIEW

**Comment by gorhom** [comment]
i tried to repo the issue but i couldn't, do you have a repo example ?

**Comment by christophby** [comment]
@gorhom I don't have a repo example but I just used this component:

<details>

<summary>BottomSheet.tsx component</summary>

```typescript
import {
  BottomSheetBackdrop,
  BottomSheetBackdropProps,
  BottomSheetModal,
  BottomSheetScrollView,
} from '@gorhom/bottom-sheet';
import React, {useCallback, useRef} from 'react';
import {Button, Text, View} from 'react-native';

interface Props {}

export const BottomSheet = ({}: Props) => {
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  const backdropComponent = useCallback(
    (props: BottomSheetBackdropProps) => (
      <BottomSheetBackdrop
        {...props}
        appearsOnIndex={0}
        disappearsOnIndex={-1}
      />
    ),
    [],
  );

  return (
    <View>
      <Button
        title="Open Bottom Sheet"
        onPress={() => {
          bottomSheetModalRef.current?.present();
        }}
      />

      <BottomSheetModal
        ref={bottomSheetModalRef}
        snapPoints={['25%']}
        backdropComponent={backdropComponent}>
        <BottomSheetScrollView>
          <>
            <Text>1 Lorem Ipsum</Text>
            <Text>2 Lorem Ipsum</Text>
          </>
        </BottomSheetScrollView>
      </BottomSheetModal>
    </View>
  );
};

```

</details>

I'm using

```
"@gorhom/bottom-sheet": "^4.5.1",
"react-native": "0.68.2",
"react-native-gesture-handler": "^2.14.0",
"react-native-reanimated": "^2.8.0",
```

https://github.com/gorhom/react-native-bottom-sheet/assets/12933672/2ef28755-f2e3-4c5f-afdb-5de23cdceaaf

File: src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx [hunk 1]
```diff
@@ -53,6 +61,16 @@ const BottomSheetBackdropComponent = ({
   >(enableTouchThrough ? 'none' : 'auto');
   //#endregion
 
+  //#region effects
+  useEffect(() => {
```
Comment (gorhom) [inline src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx]: could you move this hook to the region at the end `effects`

**Review by gorhom — CHANGES_REQUESTED** [review]

**Comment by gorhom** [comment]
looks good, i just left a code styling comment, once it is addressed im going to merge this PR into `v4` & `v5`

**Review by gorhom — APPROVED** [review]

**Comment by christophby** [comment]
Thank you for merging
