### PR TITLE
fix(#2455): wrong index reported by modal + TextInput + autofocus

### LINKED ISSUE #2455: [Bug]: wrong index reported by modal + TextInput + autofocus (v5.2.6)
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS

### What happened?

[v5.2.6] BottomSheetModal onChange is reporting corrupted index on mount when we have TextInput + autofocus.

That also breaks `keyboardBlurBehavior="restore"`

This issue might be related to this [comment](https://github.com/gorhom/react-native-bottom-sheet/issues/2452#issuecomment-3258161311) about `invariant` throwing errors for unexpected index.

### Reproduction steps

- Just open the modal and see the console reporting a big number for index
- Verify that `keyboardBlurBehavior="restore"` doesn't work when you tap "return" to dismiss the keyboard

### Reproduction sample

https://snack.expo.dev/@pakerwreah/bottom-sheet-modal---wrong-index

### Relevant log output

```shell
iPhone: handleSheetChanges 774 // on open
iPhone: handleSheetChanges 0   // on collapse
iPhone: handleSheetChanges -1  // on close
```

### PR DESCRIPTION
**Pull request by pakerwreah**
Fix #2455

## Motivation

The new fallback logic to fix TextInput with autofocus is mixing "position" with "index", leading to corrupted behavior.
(see issue for more details)

### CODE REVIEW

File: src/components/bottomSheet/BottomSheet.tsx [hunk 1]
```diff
@@ -659,7 +659,12 @@ const BottomSheetComponent = forwardRef<BottomSheet, BottomSheetProps>(
           status === KEYBOARD_STATUS.SHOWN &&
           position !== closedDetentPosition
         ) {
-          index = highestDetentPosition ?? DEFAULT_KEYBOARD_INDEX;
+          if (detents !== undefined && highestDetentPosition !== undefined) {
+            index = detents.indexOf(highestDetentPosition);
+          }
+          if (index === -1) {
+            index = DEFAULT_KEYBOARD_INDEX;
+          }
```
Comment (pakerwreah) [inline src/components/bottomSheet/BottomSheet.tsx:667]: I kept this "default index" fallback, but tbh I'm not sure what is its purpose.
I'd rather have `-1` instead of a "random" number if things go bad.

**Comment by pakerwreah** [comment]
not stale

**Comment by pakerwreah** [comment]
not stale

**Comment by pakerwreah** [comment]
not stale

**Comment by edisoni1995** [comment]
This commit for me fixes the issue where modal is not returning to bottom after keyboard is closed.

**Comment by pakerwreah** [comment]
¯\\\_(ツ)\_/¯

**Comment by g4rb4g3** [comment]
I'm facing the exact same issue, instead of the index the position is passed to handleOnAnimate, I added some logging and get this:
```
animateToPosition calling handleOnAnimate(321, 321)
```

I definitely do not have 321 snap points. So I wonder why this is PR is stale, it should have been merged already imho. Thanks @pakerwreah for this, I didn't see the issue anymore with your changes. 😃 

@gorhom Could you please have a look at this? Thank you very much!

**Review by g4rb4g3 — APPROVED** [review]

**Comment by pakerwreah** [comment]
not stale

**Review by gorhom — COMMENTED** [review]
thanks @pakerwreah
